version: "3.3"
services:
  fpm:
    image: zoldygan:fpm
    restart: always
    networks:
      - default
    volumes:
      - /opt/docker/data/www:/var/www/ #:ro

networks:
  default:
    external:
     name: backend
