version: "3.3"
services:
  gfashion:
    image: zoldygan:gfashion
    restart: always
    networks:
      - backend
    ports:
      - "15000:5000"

networks:
  backend:
    external:
     name: backend
