version: "3.3"
services:
  mysql:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql
    volumes:
      - /opt/docker/config/mysql/mysql_root_password.secret:/run/secrets/mysql:ro
      - /opt/docker/data/mysql:/var/lib/mysql

  # adminer:
  #   image: adminer:4
  #   # restart: always
  #   networks:
  #     - frontend
  #   ports:
  #     - 18080:8080

  #       # networks:
  #       #   backend:
  #       #   frontend:

networks:
  backend:
    external:
     name: backend
