version: "3.3"
services:
  nginx:
    image: nginx:1.21
    restart: always
    networks:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/docker/data/nginx/configs/:/etc/nginx/:ro
      - /opt/docker/data/www:/usr/share/nginx:ro
      - /opt/docker/data/nginx/modules:/usr/lib/nginx/modules:ro
      - /opt/docker/config/nginx/auth:/etc/nginx/auth:ro
      - /opt/docker/config/nginx/certs:/etc/nginx/certs:ro
      - /var/log/nginx:/var/log/nginx

networks:
  backend:
    external:
     name: backend
