version: "3.3"
services:
  ngrok:
    image: ngrok:zoldygan
    command: ngrok http -host-header=berozgarx.io 10080
    restart: always
    network_mode: host
    volumes:
      - /opt/docker/config/ngrok/authtoken:/root/.ngrok2/ngrok.yml:ro
